version: '3'

services:
  app:
    build: .
    ports:
      - "80:8000"
    depends_on:
      mongodb:
        condition: service_healthy
  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongodatamds02:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mongodatamds02:
